// Service worker: network first, cache as fallback, so the app works offline.
const CACHE = 'verbos-v1';

// PRECACHE:START (generated by scripts/precache.mjs)
const PRECACHE = [
  "./",
  "index.html",
  "manifest.webmanifest",
  "content/lessons/01-present-regular.md",
  "content/lessons/02-present-core-irregulars.md",
  "content/lessons/03-present-stem-changes.md",
  "content/lessons/04-present-yo-forms.md",
  "content/lessons/05-gerund.md",
  "content/lessons/06-preterite-regular.md",
  "content/lessons/07-preterite-spelling-changes.md",
  "content/lessons/08-preterite-irregular.md",
  "content/lessons/09-preterite-stem-changes.md",
  "content/lessons/10-imperfect.md",
  "content/lessons/11-present-perfect.md",
  "content/lessons/12-future.md",
  "content/lessons/13-conditional.md",
  "content/lessons/14-affirmative-imperative.md",
  "content/lessons/15-present-subjunctive-regular.md",
  "content/lessons/16-present-subjunctive-irregular.md",
  "content/lessons/17-negative-imperative.md",
  "content/lessons/18-pluperfect.md",
  "content/lessons/19-compound-future.md",
  "content/lessons/20-imperfect-subjunctive.md",
  "content/lessons/21-compound-subjunctive.md",
  "data/additions.json",
  "data/alternates.json",
  "data/curriculum.json",
  "data/top-verbs.json",
  "data/vendor/spanish-verbs/template.json",
  "data/vendor/spanish-verbs/verbs.json",
  "icons/apple-touch-icon.png",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/icon-maskable-512.png",
  "icons/icon.svg",
  "src/app.js",
  "src/components/accentKeys.js",
  "src/components/lesson.js",
  "src/components/quizRunner.js",
  "src/components/tenseName.js",
  "src/components/verbTable.js",
  "src/engine/check.js",
  "src/engine/conjugate.js",
  "src/engine/diff.js",
  "src/engine/load.js",
  "src/engine/quiz.js",
  "src/engine/schedule.js",
  "src/engine/tenses.js",
  "src/lib/h.js",
  "src/lib/marked.esm.js",
  "src/main.js",
  "src/store/store.js",
  "src/styles.css",
  "src/views/level.js",
  "src/views/levels.js",
  "src/views/practice.js",
  "src/views/progress.js",
  "src/views/review.js",
  "src/views/settings.js",
  "src/views/verbs.js"
];
// PRECACHE:END

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  event.respondWith(
    fetch(req)
      .then((res) => {
        if (res.ok) {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(req, copy));
        }
        return res;
      })
      .catch(() => caches.match(req, { ignoreSearch: true }).then((hit) => hit ?? caches.match('./'))),
  );
});
