// Writes the list of app files into sw.js so the service worker can cache them.
// Run after adding or removing files: node scripts/precache.mjs
import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

export const ROOT = fileURLToPath(new URL('..', import.meta.url));
const DIRS = ['src', 'data', 'content', 'icons'];
const FILES = ['./', 'index.html', 'manifest.webmanifest'];

/** @param {string} dir */
function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const p = join(dir, name);
    return statSync(p).isDirectory() ? walk(p) : [p];
  });
}

export function precacheList() {
  const files = DIRS.flatMap((d) => walk(join(ROOT, d)))
    .map((p) => relative(ROOT, p).split('\\').join('/'))
    .filter((p) => !p.endsWith('.DS_Store') && !p.endsWith('.map') && !p.endsWith('SOURCE.md'))
    .sort();
  return [...FILES, ...files];
}

export function render(list) {
  return `// PRECACHE:START (generated by scripts/precache.mjs)\nconst PRECACHE = ${JSON.stringify(list, null, 2)};\n// PRECACHE:END`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const sw = join(ROOT, 'sw.js');
  const src = readFileSync(sw, 'utf8');
  const out = src.replace(/\/\/ PRECACHE:START[\s\S]*?\/\/ PRECACHE:END/, render(precacheList()));
  writeFileSync(sw, out);
  console.log(`sw.js: ${precacheList().length} files`);
}
